## 异常处理

当` JavaScript `引擎执行代码时，可能会发生各种错误，当错误发生时，`JavaScript`引擎通常会停止，并生成一个错误消息，及`JavaScript `将抛出一个错误

- `try` 语句测试代码块的错误
- `catch` 语句处理错误
- `throw` 语句创建自定义错误
- `finally` 语句在 `try `和`catch` 语句之后，无论是否有触发异常，该语句都会执行

```js
try {
    ...    //异常的抛出
} catch(e) {
    ...    //异常的捕获与处理
} finally {
    ...    //结束处理
}
```

